package dto;
// Generated May 20, 2019 12:22:56 PM by Hibernate Tools 4.3.1

import dto.common.IDTO;
import dto.common.IName;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name = "orderstatus",
       catalog = "toymanager"
)
public class OrderStatus implements Serializable, IDTO, IName {
    private long id;
    private String name;
    private Set<Order> orders;

    public OrderStatus() {
        this.orders = new HashSet<>(0);
    }

    public OrderStatus(long id,
                       String name) {
        this.orders = new HashSet<>(0);
        this.id = id;
        this.name = name;
    }

    public OrderStatus(long id,
                       String name,
                       Set<Order> orders) {
        this.orders = new HashSet<>(0);
        this.id = id;
        this.name = name;
        this.orders = orders;
    }

    @Id
    @Column(name = "Id",
            unique = true,
            nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "Name",
            nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY,
               mappedBy = "orderstatus")
    public Set<Order> getOrders() {
        return this.orders;
    }

    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }
}
