package dto;
// Generated May 20, 2019 12:22:56 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserStatus generated by hbm2java
 */
@Entity
@Table(name = "userstatus",
       catalog = "toymanager"
)
public class UserStatus implements java.io.Serializable {
    private long id;
    private String name;
    private Set<User> users;

    public UserStatus() {
        this.users = new HashSet<>(0);
    }

    public UserStatus(long id,
                      String name) {
        this.users = new HashSet<>(0);
        this.id = id;
        this.name = name;
    }

    public UserStatus(long id,
                      String name,
                      Set<User> users) {
        this.users = new HashSet<>(0);
        this.id = id;
        this.name = name;
        this.users = users;
    }

    @Id
    @Column(name = "Id",
            unique = true,
            nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "Name",
            nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY,
               mappedBy = "userstatus")
    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }
}
